# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ExpensesDivider' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'SwiftLint'
  pod 'Firebase/Messaging'

end
